name: "$(SourceBranchName)+$(BuildID)"

pool:
  name: 'AWS-ECS'

trigger:
  branches:
    include:
      - tags/refs/v*
      - refs/heads/release
      - refs/heads/hotfix
  tags:
    include:
      - v*

pr:
  branches:
    include: ['*']

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge-fixed
      endpoint: NHSDigital (63)

variables:
  - template: project.yml
extends:
  template: azure/common/apigee-build.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
