name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge-fixed
      endpoint: NHSDigital (63)

schedules:
  - cron: 0 2 * * *
    displayName: 2am daily
    branches:
      include: ['master']
    always: true

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml
  - name: SERVICE_ARTIFACT_NAME
    value: ''

steps:
  - template: ./templates/teams-alert-setup.yml
    parameters:
      webhook_uri: 'ALERTS_PROD_API_WEBHOOK_URI'

  - template: ./templates/run-tests.yml
    parameters:
      nightly: true
      environment: 'int'
      test_command: 'make integration-test'

  - template: ./templates/teams-alert.yml
    parameters:
      title: 'Integration'
      webhook_uri: 'ALERTS_PROD_API_WEBHOOK_URI'