name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

parameters:
  - name: DISABLE_VERSION_OVERRIDE
    displayName: Disable version override
    type: boolean
    default: false

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge-fixed
      endpoint: NHSDigital (63)

schedules:
  - cron: 0 2 * * *
    displayName: 2am daily
    branches:
      include: ['release']
    always: true

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml
  - name: SERVICE_ARTIFACT_NAME
    value: ''

steps:
  - ${{ if parameters.DISABLE_VERSION_OVERRIDE }}:
    - template: ./templates/checkout-latest-release.yml
      parameters:
        environment: 'internal-dev-sandbox'

  - template: ./templates/teams-alert-setup.yml
    parameters:
      webhook_uri: 'ALERTS_DEV_API_WEBHOOK_URI'

  - template: ./templates/run-tests.yml
    parameters:
      nightly: True
      environment: 'internal-dev-sandbox'
      test_command: 'make internal-sandbox-test'
      unit_test_report_name: 'sandbox/sandbox-unit-report.xml'

  - template: ./templates/teams-alert.yml
    parameters:
      title: 'Internal Dev Sandbox'
      webhook_uri: 'ALERTS_DEV_API_WEBHOOK_URI'