name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge-fixed
      endpoint: NHSDigital

schedules:
  - cron: 0 2 * * *
    displayName: 2am daily
    branches:
      include: ['release']
    always: true

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml
  - name: SERVICE_ARTIFACT_NAME
    value: ''

extends:
  template: ./templates/run-tests.yml
  parameters:
    nightly: True
    environment: 'internal-dev-sandbox'
    test_command: 'make internal-sandbox-test'
    unit_test_report_name: 'sandbox/sandbox-unit-report.xml'