name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital (63)

schedules:
  - cron: '*/10 * * * *'
    displayName: every 10 minutes
    branches:
      include: ['release']
    always: true

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml
  - name: SERVICE_ARTIFACT_NAME
    value: ''

steps:

  - template: ./templates/teams-alert-setup.yml
    parameters:
      webhook_uri: 'ALERTS_PROD_API_WEBHOOK_URI'

  - bash: |
      make install-python && make mtls-test

  - template: ./templates/teams-alert.yml
    parameters:
      title: 'Integration'
      webhook_uri: 'ALERTS_PROD_API_WEBHOOK_URI'
