[project]
python = "^3.8"

[tool.poetry]
name = "communications-manager"
version = "0.0.1-alpha"
description = "Public facing API for the Communications Manager service"
authors = [
    "NHS Digital"
]
readme = "README.md"
license = "MIT"
repository = "https://github.com/NHSDigital/communications-manager-api"
homepage = "https://digital.nhs.uk/developer/api-catalogue/communications-manager"
keywords = ["healthcare", "uk", "nhs", "communications", "email", "sms", "letter"]


[tool.poetry.dependencies]
python = "^3.8"
pytest-nhsd-apim = "^3.3.11"
pytest-xdist = "^3.5.0"
pre-commit = "^3.5.0"
pytest-rerunfailures = "^12.0"
locust = "^2.23.1"
sphinx = "7.1.2"
sphinx-markdown-builder = "^0.6.5"
notifications-python-client = "^9.0.0"
polling = "^0.3.2"

[tool.poetry.dev-dependencies]
flake8 = "^5.0.4"
black = "^23.12"
pip-licenses = "^4.3.3"
jinja2 = "^3.1.3"
pyyaml = "^6.0"
docopt = "^0.6.2"
jsonpath-rw = "^1.4.0"
semver = "^3.0.2"
gitpython = "^3.1.41"
pytest = "^6.2.0"
coverage = "^7.4"
aiohttp = "^3.9.1"
pytest-asyncio = "^0.20.3"

[tool.poetry.scripts]
