openapi: 3.0.0
info:
  version: "3.0"
  title: NHS Notify API
  description:
    $ref: documentation/APIDescription.md
  contact:
    name: NHS Notify API Support
    url: "https://digital.nhs.uk/developer/help-and-support"
    email: api.management@nhs.net
servers:
  - url: "https://sandbox.api.service.nhs.uk/comms"
    description: Sandbox environment
  - url: "https://int.api.service.nhs.uk/comms"
    description: Integration test environment
  - url: "https://api.service.nhs.uk/comms"
    description: Production environment
paths:
  /v1/message-batches:
    post:
      $ref: endpoints/create_message_batch.yaml
  /v1/messages:
    post:
      $ref: endpoints/create_message.yaml
  /v1/messages/{messageId}:
    parameters:
      - schema:
          $ref: schemas/types/KSUID.yaml
        name: messageId
        in: path
        required: true
        description: The unique identifier for the message
    get:
      $ref: endpoints/get_message.yaml
  /comms/channels/nhsapp/accounts:
    parameters:
      - schema:
          $ref: schemas/types/ODSOrganisationCode.yaml
        name: ods-organisation-code
        in: query
        required: true
        description: The Organisation Data Service (ODS) code of the GP practice for which to retrieve a list of NHS App users. Not case sensitive.
      - schema:
          $ref: schemas/types/Page.yaml
        name: page
        in: query
        required: false
        description: The ordinal number of the page of results to be retrieved. If omitted, the first page of results will be returned. Use the links section in the response body to determine whether any further pages of results exist.
    get:
      $ref: endpoints/get_nhsapp_account_details.yaml
  /callbacks:
    post:
      $ref: callbacks/message_subscriptions.yaml
      tags: ['Callbacks']
