openapi: 3.0.0
info:
  version: "3.0"
  title: NHS Notify API
  description:
    $ref: documentation/APIDescription.md
  contact:
    name: NHS Notify API Support
    url: "https://digital.nhs.uk/developer/help-and-support"
    email: api.management@nhs.net
servers:
  - url: "https://sandbox.api.service.nhs.uk/comms"
    description: Sandbox environment
  - url: "https://int.api.service.nhs.uk/comms"
    description: Integration test environment
  - url: "https://api.service.nhs.uk/comms"
    description: Production environment
paths:
  /v1/message-batches:
    post:
      $ref: endpoints/create_message_batch.yaml
  /v1/messages:
    post:
      $ref: endpoints/create_message.yaml
  /v1/messages/{messageId}:
    parameters:
      - schema:
          $ref: schemas/types/KSUID.yaml
        name: messageId
        in: path
        required: true
        description: The unique identifier for the message
    get:
      $ref: endpoints/get_message.yaml
  /callbacks:
    x-spec-publication:
      try-this-api:
        disabled: true
    post:
      $ref: callbacks/message_subscriptions.yaml
      tags: ['Callbacks']
