env:
  contexts:
    - name: Sandbox
      urls:
        - https://sandbox.api.service.nhs.uk/comms # the actual url used for the scan is defined in the openapi job below
    - name: IntegrationUnauthenticated
      urls:
        - https://int.api.service.nhs.uk/comms # the actual url used for the scan is defined in the openapi job below
    - name: IntegrationAuthenticated
      urls:
        - https://int.api.service.nhs.uk/comms # the actual url used for the scan is defined in the openapi job below
      authentication:
        method: 'script'
        parameters:
          url: https://int.api.service.nhs.uk/oauth2/token
          script: 'scripts/authentication/get_bearer_token.js'
          scriptEngine: 'Graal.js'
        verification:
          method: 'response'
          loggedOutRegex: '401 Unauthorized'
      users:
        - name: Integration
          credentials:
            kid: local
            api_key: "${INTEGRATION_API_KEY}"
            private_key: "${INTEGRATION_PRIVATE_KEY_CONTENTS}"
    - name: ProdUnauthenticated
      urls:
        - https://api.service.nhs.uk/comms # the actual url used for the scan is defined in the openapi job below
    - name: ProdAuthenticated
      urls:
        - https://api.service.nhs.uk/comms # the actual url used for the scan is defined in the openapi job below
      authentication:
        method: 'script'
        parameters:
          url: https://api.service.nhs.uk/oauth2/token
          script: 'scripts/authentication/get_bearer_token.js'
          scriptEngine: 'Graal.js'
        verification:
          method: 'response'
          loggedOutRegex: '401 Unauthorized'
      users:
        - name: Prod
          credentials:
            kid: prod-1
            api_key: "${PRODUCTION_API_KEY}"
            private_key: "${PRODUCTION_PRIVATE_KEY_CONTENTS}"
  parameters:
    failOnError: true
    failOnWarning: true
    progressToStdout: true

jobs:
  # load our authentication and httpsender script
  - type: script
    parameters:
      action: 'add'
      type: 'httpsender'
      engine: 'Graal.js'
      name: 'add_bearer_token'
      file: 'scripts/httpsender/add_bearer_token.js'
  - type: script
    parameters:
      action: 'add'
      type: 'authentication'
      engine: 'Graal.js'
      name: 'get_bearer_token'
      file: 'scripts/authentication/get_bearer_token.js'

  # load the zap specific openapi specification
  - type: openapi
    parameters:
      apiFile: '/zap/wrk/build/communications-manager-zap.json'
      targetUrl: https://sandbox.api.service.nhs.uk/comms
      context: Sandbox
  - type: openapi
    parameters:
      apiFile: '/zap/wrk/build/communications-manager-zap.json'
      targetUrl: https://int.api.service.nhs.uk/comms
      context: IntegrationUnauthenticated
  - type: openapi
    parameters:
      apiFile: '/zap/wrk/build/communications-manager-zap.json'
      targetUrl: https://int.api.service.nhs.uk/comms
      context: IntegrationAuthenticated
  - type: openapi
    parameters:
      apiFile: '/zap/wrk/build/communications-manager-zap.json'
      targetUrl: https://api.service.nhs.uk/comms
      context: ProdUnauthenticated
  - type: openapi
    parameters:
      apiFile: '/zap/wrk/build/communications-manager-zap.json'
      targetUrl: https://api.service.nhs.uk/comms
      context: ProdAuthenticated


  # run an active scan on sandbox
  - type: activeScan
    parameters:
      policy: API
      context: Sandbox
      scanHeadersAllRequests: true
      delayInMs: 500
      threadPerHost: 1

  # run an active scan on integration, using unauthenticated calls
  - type: activeScan
    parameters:
      policy: API
      context: IntegrationUnauthenticated
      scanHeadersAllRequests: true
      delayInMs: 500
      threadPerHost: 1

  # run an active scan on integration, using authenticated calls
  - type: activeScan
    parameters:
      policy: API
      context: IntegrationAuthenticated
      user: Integration
      scanHeadersAllRequests: true
      delayInMs: 500
      threadPerHost: 1

   # run an active scan on prod, using unauthenticated calls
  - type: activeScan
    parameters:
      policy: API
      context: ProdUnauthenticated
      scanHeadersAllRequests: true
      delayInMs: 500
      threadPerHost: 1

  # run an active scan on prod, using authenticated calls
  - type: activeScan
    parameters:
      policy: API
      context: ProdAuthenticated
      user: Prod
      scanHeadersAllRequests: true
      delayInMs: 500
      threadPerHost: 1

  # generate our custom JSON report
  - type: report
    parameters:
      template: 'comms-manager-json'
      reportDir: '/zap/tmp'
      reportFile: 'zap-report.json'
    risks:
      - high
      - medium
      - low
      - info
    confidences:
      - high
      - medium
      - low
      - falsepositive